/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Perpustakaan.ui;

import Perpustakaan.model.Buku;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Perpustakaan.model.BukuManager;
import config.ConnectionHelper;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JRadioButton;

/**
 *
 * @author YOGA SAPUTRA
 */
    
public class tambahbuku extends javax.swing.JFrame {      
    String formTittle="";
    int BukuID = 0;
    Buku BukuGlobal;
    
    public tambahbuku() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
    
   public tambahbuku (String tittle, int id){
        initComponents();
        setLocationRelativeTo(null);
        addbook.setText(tittle);
        formTittle = tittle;
        BukuID = id;
        
        try {
            setBookToComponent(BukuID);
        } catch (SQLException e){
            Logger.getLogger(tambahbuku.class.getName()).log(Level.SEVERE,null,e);
        }
    }
   private void setBookToComponent(int bookID)throws SQLException{
       Buku buku = BukuManager.showbook(bookID);
       buku.setId_buku(bookID);
       judul.setText(buku.getJudul_buku());
       pengarang.setText(buku.getPengarang());
       jComboBox1.setSelectedItem(String.valueOf(buku.getTahun_terbit()));
       
       if (buku.getPenerbit().equalsIgnoreCase("Jember Pustakan")){
           jRadioButton1.setSelected(true);
       }else if(buku.getPenerbit().equalsIgnoreCase("Gramedia")){
           jRadioButton2.setSelected(true);
       }else if(buku.getPenerbit().equalsIgnoreCase("Polije press")){
           jRadioButton3.setSelected(true);
       }else if(buku.getPenerbit().equalsIgnoreCase("RRI library")){
           jRadioButton4.setSelected(true);
       }
   }
//     public void updatebook(){
//         try {
//             Connection conn = ConnectionHelper.getConnection();
//             Statement stm = conn.createStatement();
//             
//            
//             String sql = "UPDATE  buku SET judul_buku ="+judul+",pengarang = "+pengarang+", penerbit="+jrad+", "
//                     + "tahun_terbit = "+jComboBox1+" WHERE id_buku=?";               
//         } catch (Exception e) {
//         }
//     }
        
     public void actionPerform(){
         
     }
    
    private boolean validateInput() throws SQLException{
        boolean isComleted = false;
        
        Buku buku = new Buku();
        
        if(judul.getText().isEmpty()){
            isComleted = false;
            judul.requestFocus();
        }else{
            buku.setJudul_buku(judul.getText());
            isComleted = true;
        }
        
        if (pengarang.getText().isEmpty()) {
            isComleted = false;
            pengarang.requestFocus();
        }else{
            buku.setPengarang(pengarang.getText());
            isComleted = true;
        }
        
        if (jRadioButton1.isSelected()) {
            buku.setPenerbit(jRadioButton1.getText());
            isComleted = true;
        }else if(jRadioButton2.isSelected()){
            buku.setPenerbit(jRadioButton2.getText());
            isComleted = true;
        }else if(jRadioButton3.isSelected()){
            buku.setPenerbit(jRadioButton3.getText());
            isComleted = true;
        }else if (jRadioButton4.isSelected()){
            buku.setPenerbit(jRadioButton4.getText());
            isComleted = true;
        }else{
            isComleted = false;
        }
        
        buku.setTahun_terbit(Integer.parseInt(jComboBox1.getSelectedItem().toString()));
        
        if(formTittle.equalsIgnoreCase("Update buku")){
            buku.setId_buku(BukuID);
        }
        
        BukuGlobal = buku;
        
        if(!isComleted){
            showMassage("data harus dilengkapi",2);
            return false;
        }else{
            dispose();
            return true;
        }
    }
    
 public void showMassage(String Message, int type){
        if(type == 1){
            JOptionPane.showMessageDialog(this,Message ,"Sukses", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,Message,"Gagal",JOptionPane.ERROR_MESSAGE);
        }
    }    
 
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pengarang = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        jlabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addbook = new javax.swing.JLabel();

        jRadioButton1.setText("Jember pustaka");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Gramedia");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Polije Press");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("RRI libray");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbatal.setText("batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        jLabel2.setText("Judul");

        jLabel3.setText("Pengarang");

        judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulActionPerformed(evt);
            }
        });

        jlabel.setText("Penerbit");

        jLabel5.setText("Tahun Terbit");

        addbook.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        addbook.setText("ADD BOOK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(addbook)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jlabel)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(btnsimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnbatal))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton3))))
                        .addGap(31, 31, 31))
                    .addComponent(pengarang)
                    .addComponent(judul))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnbatal))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        dispose();
        
      
    }//GEN-LAST:event_btnbatalActionPerformed
    void Penerbit(){
        String penerbit = null;
       if (penerbit.equals("Jember pustaka")) {
            jRadioButton1.setSelected(true);
        }else if(penerbit.equals("Gramedia")){
            jRadioButton2.setSelected(true);
        }else if(penerbit.equals("Polije Press")){
            jRadioButton3.setSelected(true);
        }else if (penerbit.equals("RRI library")){
            jRadioButton4.setSelected(true);
    }
    }
    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed

//        try {
//        Connection conn = ConnectionHelper.getConnection();
//        Statement stm = conn.createStatement();
//        String sql ="INSERT INTO buku(judul_buku,pengarang , penerbit, tahun_terbit) "
//                + "VALUES ("+judul.getText()+","+pengarang.getText()+","+penerbit+","+jComboBox1.getSelectedItem()+")";
//        stm.executeUpdate(sql);
//            JOptionPane.showMessageDialog(this, "data berhasil ditambahkan","sukses",JOptionPane.WARNING_MESSAGE);
//        } catch (Exception e) {
//            System.out.println(e);
//        } 
                   if (formTittle.equalsIgnoreCase("Update buku")) {
                try {
                    if (validateInput()) {
                        BukuManager.updateBook(BukuGlobal);
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
        }else{
                try {
                    if (validateInput()) {
                        BukuManager.insertBook(BukuGlobal);
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
      
        
        
    }//GEN-LAST:event_btnsimpanActionPerformed
      
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        penerbit = "jember pustaka";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        penerbit ="Gramedia";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        penerbit = "Polije Press";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        penerbit="RRI Library";
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahbuku().setVisible(true);
            }
        });
    }
    private String penerbit;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addbook;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel jlabel;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField pengarang;
    // End of variables declaration//GEN-END:variables
}
